ldap:
  host: "your-pingdirectory-host"
  port: 1389
  bind_dn: "cn=Directory Manager"
  bind_password: "your-password"
  username: "admin"
  password: "Testingadminformvp"
  base_dn: "dc=example,dc=com" 